#!/usr/bin/env bash
# Script indefinitely writes "I am alive" to the file /tmp/my_process
# with 2-second pause between each message

while true; do
    sudo bash -c 'echo "I am alive!" >> /tmp/my_process'
    sleep 2
done
