#!/usr/bin/env bash
# Show 4  then "bad luck from China" for 4th iteration
# Shows 9 then "bad luck from Japan" for 9th iteration
# Shows 17 then "bad luck from Italy" for 17th iteration
# Must use while loop and case statement

k=1

while [ $k -le 20 ]
do
	echo "$k"

	case $k in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
	((k++))
done
