#!/usr/bin/env bash
# Shows time for 12 hours and 59 minutes
# Shows hours from 0 to 12
# Shows minutes from 1 to 59
# Must use the while loop

h=0

while [ $h -le 12 ]
do
	echo "Hour: $h"

	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((h++))
done
